// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Las migraciones necesitan una conexión directa (sin el pooler de
  // transacciones) para poder tomar el lock de migración. La app en
  // ejecución sigue usando DATABASE_URL (con pooler) vía src/lib/prisma.ts.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
